//
// DO NOT MODIFY version.hpp, it is automatically generated by cmake
// MODIFY version.hpp.in as needed
//

#ifndef QoZ_VERSION_HPP
#define QoZ_VERSION_HPP

#define QoZ_NAME "QoZ"
#define QoZ_VER  "0.1.0.0"
#define QoZ_VER_MAJOR 0
#define QoZ_VER_MINOR 1
#define QoZ_VER_PATCH 0
#define QoZ_VER_TWEAK 0

#endif //QoZ_VERSION_HPP
