//
// DO NOT MODIFY version.hpp, it is automatically generated by cmake
// MODIFY version.hpp.in as needed
//

#ifndef QoZ_VERSION_HPP
#define QoZ_VERSION_HPP

#define QoZ_NAME "QoZ"
#define QoZ_VER  "2.0.0.0"
#define QoZ_VER_MAJOR 2
#define QoZ_VER_MINOR 0
#define QoZ_VER_PATCH 0
#define QoZ_VER_TWEAK 0

#endif //QoZ_VERSION_HPP
